### ISSUE TITLE
Can't drop in ANY .mca file into chunk viewer on ANY browser

### ISSUE THREAD

**Issue by ynnarg** [Pessimistress/minecraft-chunk-viewer#33]
I cannot upload/drag in any .mca files on any browser into the Minecraft chunk viewer. I get the following error:

`
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at bundle.js:45:442507
    at bundle.js:45:442561
    at t._onDataLoaded (bundle.js:45:442608)
    at FileReader.i.onload (bundle.js:45:443870)
`

**Comment by YubaC** [comment]
I also encountered this problem.
However, demo web page works well when I drop a mca file from version 1.7.10.
It's said that **MOJANG changed the storage format after 1.18**.
I don't know if this is the root of the problem.
Hope this will help you.
